#!/bin/sh

#PBS -q cuda
#PBS -N ifml-pytorch
#PBS -l nodes=denbi1-int
#PBS -V
#PBS -M jakob@kreft-mail.de
#PBS -m bea
#PBS -e ~/ifml/qsub/stderr.err
#PBS -o ~/ifml/qsub/stdout.log

source ~/.bashrc
conda activate pytorch
python3 ~/ifml/ifml_project/jay.py